// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: serviciosCancion.proto

package serviciosCancion

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mensajes existentes...
type Vacio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vacio) Reset() {
	*x = Vacio{}
	mi := &file_serviciosCancion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vacio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vacio) ProtoMessage() {}

func (x *Vacio) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosCancion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vacio.ProtoReflect.Descriptor instead.
func (*Vacio) Descriptor() ([]byte, []int) {
	return file_serviciosCancion_proto_rawDescGZIP(), []int{0}
}

type Genero struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Genero) Reset() {
	*x = Genero{}
	mi := &file_serviciosCancion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Genero) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genero) ProtoMessage() {}

func (x *Genero) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosCancion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genero.ProtoReflect.Descriptor instead.
func (*Genero) Descriptor() ([]byte, []int) {
	return file_serviciosCancion_proto_rawDescGZIP(), []int{1}
}

func (x *Genero) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Genero) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

type ListaGeneros struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generos       []*Genero              `protobuf:"bytes,1,rep,name=generos,proto3" json:"generos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListaGeneros) Reset() {
	*x = ListaGeneros{}
	mi := &file_serviciosCancion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListaGeneros) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListaGeneros) ProtoMessage() {}

func (x *ListaGeneros) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosCancion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListaGeneros.ProtoReflect.Descriptor instead.
func (*ListaGeneros) Descriptor() ([]byte, []int) {
	return file_serviciosCancion_proto_rawDescGZIP(), []int{2}
}

func (x *ListaGeneros) GetGeneros() []*Genero {
	if x != nil {
		return x.Generos
	}
	return nil
}

// Agrega estos nuevos mensajes
type PeticionGeneroID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeticionGeneroID) Reset() {
	*x = PeticionGeneroID{}
	mi := &file_serviciosCancion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeticionGeneroID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeticionGeneroID) ProtoMessage() {}

func (x *PeticionGeneroID) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosCancion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeticionGeneroID.ProtoReflect.Descriptor instead.
func (*PeticionGeneroID) Descriptor() ([]byte, []int) {
	return file_serviciosCancion_proto_rawDescGZIP(), []int{3}
}

func (x *PeticionGeneroID) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RespuestaGenerosDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensaje       string                 `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Codigo        int32                  `protobuf:"varint,2,opt,name=codigo,proto3" json:"codigo,omitempty"`
	ObjGeneros    []*Genero              `protobuf:"bytes,3,rep,name=objGeneros,proto3" json:"objGeneros,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespuestaGenerosDTO) Reset() {
	*x = RespuestaGenerosDTO{}
	mi := &file_serviciosCancion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaGenerosDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaGenerosDTO) ProtoMessage() {}

func (x *RespuestaGenerosDTO) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosCancion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaGenerosDTO.ProtoReflect.Descriptor instead.
func (*RespuestaGenerosDTO) Descriptor() ([]byte, []int) {
	return file_serviciosCancion_proto_rawDescGZIP(), []int{4}
}

func (x *RespuestaGenerosDTO) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *RespuestaGenerosDTO) GetCodigo() int32 {
	if x != nil {
		return x.Codigo
	}
	return 0
}

func (x *RespuestaGenerosDTO) GetObjGeneros() []*Genero {
	if x != nil {
		return x.ObjGeneros
	}
	return nil
}

type RespuestaGeneroDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensaje       string                 `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Codigo        int32                  `protobuf:"varint,2,opt,name=codigo,proto3" json:"codigo,omitempty"`
	Genero        *Genero                `protobuf:"bytes,3,opt,name=genero,proto3" json:"genero,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespuestaGeneroDTO) Reset() {
	*x = RespuestaGeneroDTO{}
	mi := &file_serviciosCancion_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaGeneroDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaGeneroDTO) ProtoMessage() {}

func (x *RespuestaGeneroDTO) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosCancion_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaGeneroDTO.ProtoReflect.Descriptor instead.
func (*RespuestaGeneroDTO) Descriptor() ([]byte, []int) {
	return file_serviciosCancion_proto_rawDescGZIP(), []int{5}
}

func (x *RespuestaGeneroDTO) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *RespuestaGeneroDTO) GetCodigo() int32 {
	if x != nil {
		return x.Codigo
	}
	return 0
}

func (x *RespuestaGeneroDTO) GetGenero() *Genero {
	if x != nil {
		return x.Genero
	}
	return nil
}

type IdGenero struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdGenero) Reset() {
	*x = IdGenero{}
	mi := &file_serviciosCancion_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdGenero) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdGenero) ProtoMessage() {}

func (x *IdGenero) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosCancion_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdGenero.ProtoReflect.Descriptor instead.
func (*IdGenero) Descriptor() ([]byte, []int) {
	return file_serviciosCancion_proto_rawDescGZIP(), []int{6}
}

func (x *IdGenero) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Cancion struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Titulo          string                 `protobuf:"bytes,2,opt,name=titulo,proto3" json:"titulo,omitempty"`
	Artista         string                 `protobuf:"bytes,3,opt,name=artista,proto3" json:"artista,omitempty"`
	AnioLanzamiento int32                  `protobuf:"varint,4,opt,name=anio_lanzamiento,json=anioLanzamiento,proto3" json:"anio_lanzamiento,omitempty"`
	Duracion        string                 `protobuf:"bytes,5,opt,name=duracion,proto3" json:"duracion,omitempty"`
	ObjGenero       *Genero                `protobuf:"bytes,6,opt,name=obj_genero,json=objGenero,proto3" json:"obj_genero,omitempty"`
	Idioma          string                 `protobuf:"bytes,7,opt,name=idioma,proto3" json:"idioma,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Cancion) Reset() {
	*x = Cancion{}
	mi := &file_serviciosCancion_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cancion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancion) ProtoMessage() {}

func (x *Cancion) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosCancion_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancion.ProtoReflect.Descriptor instead.
func (*Cancion) Descriptor() ([]byte, []int) {
	return file_serviciosCancion_proto_rawDescGZIP(), []int{7}
}

func (x *Cancion) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Cancion) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *Cancion) GetArtista() string {
	if x != nil {
		return x.Artista
	}
	return ""
}

func (x *Cancion) GetAnioLanzamiento() int32 {
	if x != nil {
		return x.AnioLanzamiento
	}
	return 0
}

func (x *Cancion) GetDuracion() string {
	if x != nil {
		return x.Duracion
	}
	return ""
}

func (x *Cancion) GetObjGenero() *Genero {
	if x != nil {
		return x.ObjGenero
	}
	return nil
}

func (x *Cancion) GetIdioma() string {
	if x != nil {
		return x.Idioma
	}
	return ""
}

type ListaCanciones struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Canciones     []*Cancion             `protobuf:"bytes,1,rep,name=canciones,proto3" json:"canciones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListaCanciones) Reset() {
	*x = ListaCanciones{}
	mi := &file_serviciosCancion_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListaCanciones) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListaCanciones) ProtoMessage() {}

func (x *ListaCanciones) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosCancion_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListaCanciones.ProtoReflect.Descriptor instead.
func (*ListaCanciones) Descriptor() ([]byte, []int) {
	return file_serviciosCancion_proto_rawDescGZIP(), []int{8}
}

func (x *ListaCanciones) GetCanciones() []*Cancion {
	if x != nil {
		return x.Canciones
	}
	return nil
}

type IdCancion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdCancion) Reset() {
	*x = IdCancion{}
	mi := &file_serviciosCancion_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdCancion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdCancion) ProtoMessage() {}

func (x *IdCancion) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosCancion_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdCancion.ProtoReflect.Descriptor instead.
func (*IdCancion) Descriptor() ([]byte, []int) {
	return file_serviciosCancion_proto_rawDescGZIP(), []int{9}
}

func (x *IdCancion) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PeticionCancionDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Titulo        string                 `protobuf:"bytes,1,opt,name=titulo,proto3" json:"titulo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeticionCancionDTO) Reset() {
	*x = PeticionCancionDTO{}
	mi := &file_serviciosCancion_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeticionCancionDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeticionCancionDTO) ProtoMessage() {}

func (x *PeticionCancionDTO) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosCancion_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeticionCancionDTO.ProtoReflect.Descriptor instead.
func (*PeticionCancionDTO) Descriptor() ([]byte, []int) {
	return file_serviciosCancion_proto_rawDescGZIP(), []int{10}
}

func (x *PeticionCancionDTO) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

type RespuestaCancionDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensaje       string                 `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Codigo        int32                  `protobuf:"varint,2,opt,name=codigo,proto3" json:"codigo,omitempty"`
	ObjCancion    *Cancion               `protobuf:"bytes,3,opt,name=obj_cancion,json=objCancion,proto3" json:"obj_cancion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespuestaCancionDTO) Reset() {
	*x = RespuestaCancionDTO{}
	mi := &file_serviciosCancion_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaCancionDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaCancionDTO) ProtoMessage() {}

func (x *RespuestaCancionDTO) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosCancion_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaCancionDTO.ProtoReflect.Descriptor instead.
func (*RespuestaCancionDTO) Descriptor() ([]byte, []int) {
	return file_serviciosCancion_proto_rawDescGZIP(), []int{11}
}

func (x *RespuestaCancionDTO) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *RespuestaCancionDTO) GetCodigo() int32 {
	if x != nil {
		return x.Codigo
	}
	return 0
}

func (x *RespuestaCancionDTO) GetObjCancion() *Cancion {
	if x != nil {
		return x.ObjCancion
	}
	return nil
}

type DetalleCancion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cancion       *Cancion               `protobuf:"bytes,1,opt,name=cancion,proto3" json:"cancion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetalleCancion) Reset() {
	*x = DetalleCancion{}
	mi := &file_serviciosCancion_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetalleCancion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetalleCancion) ProtoMessage() {}

func (x *DetalleCancion) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosCancion_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetalleCancion.ProtoReflect.Descriptor instead.
func (*DetalleCancion) Descriptor() ([]byte, []int) {
	return file_serviciosCancion_proto_rawDescGZIP(), []int{12}
}

func (x *DetalleCancion) GetCancion() *Cancion {
	if x != nil {
		return x.Cancion
	}
	return nil
}

var File_serviciosCancion_proto protoreflect.FileDescriptor

const file_serviciosCancion_proto_rawDesc = "" +
	"\n" +
	"\x16serviciosCancion.proto\x12\tservicios\"\a\n" +
	"\x05Vacio\"0\n" +
	"\x06Genero\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\";\n" +
	"\fListaGeneros\x12+\n" +
	"\ageneros\x18\x01 \x03(\v2\x11.servicios.GeneroR\ageneros\"\"\n" +
	"\x10PeticionGeneroID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"z\n" +
	"\x13RespuestaGenerosDTO\x12\x18\n" +
	"\amensaje\x18\x01 \x01(\tR\amensaje\x12\x16\n" +
	"\x06codigo\x18\x02 \x01(\x05R\x06codigo\x121\n" +
	"\n" +
	"objGeneros\x18\x03 \x03(\v2\x11.servicios.GeneroR\n" +
	"objGeneros\"q\n" +
	"\x12RespuestaGeneroDTO\x12\x18\n" +
	"\amensaje\x18\x01 \x01(\tR\amensaje\x12\x16\n" +
	"\x06codigo\x18\x02 \x01(\x05R\x06codigo\x12)\n" +
	"\x06genero\x18\x03 \x01(\v2\x11.servicios.GeneroR\x06genero\"\x1a\n" +
	"\bIdGenero\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xdc\x01\n" +
	"\aCancion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06titulo\x18\x02 \x01(\tR\x06titulo\x12\x18\n" +
	"\aartista\x18\x03 \x01(\tR\aartista\x12)\n" +
	"\x10anio_lanzamiento\x18\x04 \x01(\x05R\x0fanioLanzamiento\x12\x1a\n" +
	"\bduracion\x18\x05 \x01(\tR\bduracion\x120\n" +
	"\n" +
	"obj_genero\x18\x06 \x01(\v2\x11.servicios.GeneroR\tobjGenero\x12\x16\n" +
	"\x06idioma\x18\a \x01(\tR\x06idioma\"B\n" +
	"\x0eListaCanciones\x120\n" +
	"\tcanciones\x18\x01 \x03(\v2\x12.servicios.CancionR\tcanciones\"\x1b\n" +
	"\tIdCancion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\",\n" +
	"\x12PeticionCancionDTO\x12\x16\n" +
	"\x06titulo\x18\x01 \x01(\tR\x06titulo\"|\n" +
	"\x13RespuestaCancionDTO\x12\x18\n" +
	"\amensaje\x18\x01 \x01(\tR\amensaje\x12\x16\n" +
	"\x06codigo\x18\x02 \x01(\x05R\x06codigo\x123\n" +
	"\vobj_cancion\x18\x03 \x01(\v2\x12.servicios.CancionR\n" +
	"objCancion\">\n" +
	"\x0eDetalleCancion\x12,\n" +
	"\acancion\x18\x01 \x01(\v2\x12.servicios.CancionR\acancion2\x8c\x03\n" +
	"\x12serviciosCanciones\x12P\n" +
	"\rBuscarCancion\x12\x1d.servicios.PeticionCancionDTO\x1a\x1e.servicios.RespuestaCancionDTO\"\x00\x12J\n" +
	"\x15ObtenerDetalleCancion\x12\x14.servicios.IdCancion\x1a\x19.servicios.DetalleCancion\"\x00\x12<\n" +
	"\rListarGeneros\x12\x10.servicios.Vacio\x1a\x17.servicios.ListaGeneros\"\x00\x12L\n" +
	"\x18ListarCancionesPorGenero\x12\x13.servicios.IdGenero\x1a\x19.servicios.ListaCanciones\"\x00\x12L\n" +
	"\fBuscarGenero\x12\x1b.servicios.PeticionGeneroID\x1a\x1d.servicios.RespuestaGeneroDTO\"\x00B\x13Z\x11/serviciosCancionb\x06proto3"

var (
	file_serviciosCancion_proto_rawDescOnce sync.Once
	file_serviciosCancion_proto_rawDescData []byte
)

func file_serviciosCancion_proto_rawDescGZIP() []byte {
	file_serviciosCancion_proto_rawDescOnce.Do(func() {
		file_serviciosCancion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_serviciosCancion_proto_rawDesc), len(file_serviciosCancion_proto_rawDesc)))
	})
	return file_serviciosCancion_proto_rawDescData
}

var file_serviciosCancion_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_serviciosCancion_proto_goTypes = []any{
	(*Vacio)(nil),               // 0: servicios.Vacio
	(*Genero)(nil),              // 1: servicios.Genero
	(*ListaGeneros)(nil),        // 2: servicios.ListaGeneros
	(*PeticionGeneroID)(nil),    // 3: servicios.PeticionGeneroID
	(*RespuestaGenerosDTO)(nil), // 4: servicios.RespuestaGenerosDTO
	(*RespuestaGeneroDTO)(nil),  // 5: servicios.RespuestaGeneroDTO
	(*IdGenero)(nil),            // 6: servicios.IdGenero
	(*Cancion)(nil),             // 7: servicios.Cancion
	(*ListaCanciones)(nil),      // 8: servicios.ListaCanciones
	(*IdCancion)(nil),           // 9: servicios.IdCancion
	(*PeticionCancionDTO)(nil),  // 10: servicios.PeticionCancionDTO
	(*RespuestaCancionDTO)(nil), // 11: servicios.RespuestaCancionDTO
	(*DetalleCancion)(nil),      // 12: servicios.DetalleCancion
}
var file_serviciosCancion_proto_depIdxs = []int32{
	1,  // 0: servicios.ListaGeneros.generos:type_name -> servicios.Genero
	1,  // 1: servicios.RespuestaGenerosDTO.objGeneros:type_name -> servicios.Genero
	1,  // 2: servicios.RespuestaGeneroDTO.genero:type_name -> servicios.Genero
	1,  // 3: servicios.Cancion.obj_genero:type_name -> servicios.Genero
	7,  // 4: servicios.ListaCanciones.canciones:type_name -> servicios.Cancion
	7,  // 5: servicios.RespuestaCancionDTO.obj_cancion:type_name -> servicios.Cancion
	7,  // 6: servicios.DetalleCancion.cancion:type_name -> servicios.Cancion
	10, // 7: servicios.serviciosCanciones.BuscarCancion:input_type -> servicios.PeticionCancionDTO
	9,  // 8: servicios.serviciosCanciones.ObtenerDetalleCancion:input_type -> servicios.IdCancion
	0,  // 9: servicios.serviciosCanciones.ListarGeneros:input_type -> servicios.Vacio
	6,  // 10: servicios.serviciosCanciones.ListarCancionesPorGenero:input_type -> servicios.IdGenero
	3,  // 11: servicios.serviciosCanciones.BuscarGenero:input_type -> servicios.PeticionGeneroID
	11, // 12: servicios.serviciosCanciones.BuscarCancion:output_type -> servicios.RespuestaCancionDTO
	12, // 13: servicios.serviciosCanciones.ObtenerDetalleCancion:output_type -> servicios.DetalleCancion
	2,  // 14: servicios.serviciosCanciones.ListarGeneros:output_type -> servicios.ListaGeneros
	8,  // 15: servicios.serviciosCanciones.ListarCancionesPorGenero:output_type -> servicios.ListaCanciones
	5,  // 16: servicios.serviciosCanciones.BuscarGenero:output_type -> servicios.RespuestaGeneroDTO
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_serviciosCancion_proto_init() }
func file_serviciosCancion_proto_init() {
	if File_serviciosCancion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_serviciosCancion_proto_rawDesc), len(file_serviciosCancion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_serviciosCancion_proto_goTypes,
		DependencyIndexes: file_serviciosCancion_proto_depIdxs,
		MessageInfos:      file_serviciosCancion_proto_msgTypes,
	}.Build()
	File_serviciosCancion_proto = out.File
	file_serviciosCancion_proto_goTypes = nil
	file_serviciosCancion_proto_depIdxs = nil
}
